//<auto-generated />
namespace OpenIris.UI
{
    partial class EyeTrackingPipelinePupilCRQuickSettings
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.sliderPupil = new OpenIris.UI.SliderTextControl();
            this.sliderCR = new OpenIris.UI.SliderTextControl();
            this.tableLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 1;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.Controls.Add(this.sliderCR, 0, 2);
            this.tableLayoutPanel1.Controls.Add(this.sliderPupil, 0, 1);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 4;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(567, 326);
            this.tableLayoutPanel1.TabIndex = 35;
            // 
            // sliderPupil
            // 
            this.sliderPupil.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sliderPupil.EnableValueChangedEvent = true;
            this.sliderPupil.Location = new System.Drawing.Point(4, 86);
            this.sliderPupil.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.sliderPupil.Name = "sliderPupil";
            this.sliderPupil.Size = new System.Drawing.Size(559, 71);
            this.sliderPupil.TabIndex = 0;
            this.sliderPupil.Value = 0;
            this.sliderPupil.ValueChanged += new System.EventHandler(this.sliderPupil_ValueChanged);
            // 
            // sliderCR
            // 
            this.sliderCR.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sliderCR.EnableValueChangedEvent = true;
            this.sliderCR.Location = new System.Drawing.Point(4, 167);
            this.sliderCR.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.sliderCR.Name = "sliderCR";
            this.sliderCR.Size = new System.Drawing.Size(559, 71);
            this.sliderCR.TabIndex = 1;
            this.sliderCR.Value = 0;
            this.sliderCR.ValueChanged += new System.EventHandler(this.sliderPupil_ValueChanged);
            // 
            // EyeTrackingPipelinePupilCRQuickSettings
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.tableLayoutPanel1);
            this.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.Name = "EyeTrackingPipelinePupilCRQuickSettings";
            this.Size = new System.Drawing.Size(567, 326);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private SliderTextControl sliderCR;
        private SliderTextControl sliderPupil;
    }
}
