//<auto-generated />
namespace OpenIris.UI
{
    partial class EyeTrackingPipelineJOMQuickSettings
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.imageBoxIrisRefeference = new Emgu.CV.UI.ImageBox();
            this.imageBoxIris = new Emgu.CV.UI.ImageBox();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.sliderIrisRadius = new OpenIris.UI.SliderTextControl();
            this.sliderCRThreshold = new OpenIris.UI.SliderTextControl();
            this.sliderPupilThreshold = new OpenIris.UI.SliderTextControl();
            ((System.ComponentModel.ISupportInitialize)(this.imageBoxIrisRefeference)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.imageBoxIris)).BeginInit();
            this.tableLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // imageBoxIrisRefeference
            // 
            this.imageBoxIrisRefeference.BackColor = System.Drawing.SystemColors.Control;
            this.imageBoxIrisRefeference.Dock = System.Windows.Forms.DockStyle.Fill;
            this.imageBoxIrisRefeference.FunctionalMode = Emgu.CV.UI.ImageBox.FunctionalModeOption.RightClickMenu;
            this.imageBoxIrisRefeference.Location = new System.Drawing.Point(4, 5);
            this.imageBoxIrisRefeference.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.imageBoxIrisRefeference.Name = "imageBoxIrisRefeference";
            this.imageBoxIrisRefeference.Size = new System.Drawing.Size(635, 50);
            this.imageBoxIrisRefeference.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.imageBoxIrisRefeference.TabIndex = 36;
            this.imageBoxIrisRefeference.TabStop = false;
            // 
            // imageBoxIris
            // 
            this.imageBoxIris.BackColor = System.Drawing.SystemColors.Control;
            this.imageBoxIris.Dock = System.Windows.Forms.DockStyle.Fill;
            this.imageBoxIris.FunctionalMode = Emgu.CV.UI.ImageBox.FunctionalModeOption.RightClickMenu;
            this.imageBoxIris.Location = new System.Drawing.Point(4, 65);
            this.imageBoxIris.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.imageBoxIris.Name = "imageBoxIris";
            this.imageBoxIris.Size = new System.Drawing.Size(635, 50);
            this.imageBoxIris.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.imageBoxIris.TabIndex = 37;
            this.imageBoxIris.TabStop = false;
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 1;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.Controls.Add(this.sliderIrisRadius, 0, 4);
            this.tableLayoutPanel1.Controls.Add(this.imageBoxIrisRefeference, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.sliderCRThreshold, 0, 3);
            this.tableLayoutPanel1.Controls.Add(this.imageBoxIris, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.sliderPupilThreshold, 0, 2);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 5;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 60F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 60F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(643, 334);
            this.tableLayoutPanel1.TabIndex = 38;
            // 
            // sliderIrisRadius
            // 
            this.sliderIrisRadius.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sliderIrisRadius.EnableValueChangedEvent = true;
            this.sliderIrisRadius.Location = new System.Drawing.Point(4, 267);
            this.sliderIrisRadius.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.sliderIrisRadius.Name = "sliderIrisRadius";
            this.sliderIrisRadius.Size = new System.Drawing.Size(635, 62);
            this.sliderIrisRadius.TabIndex = 44;
            this.sliderIrisRadius.Value = 0;
            this.sliderIrisRadius.ValueChanged += new System.EventHandler(this.sliderPupilThreshold_ValueChanged);
            // 
            // sliderCRThreshold
            // 
            this.sliderCRThreshold.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sliderCRThreshold.EnableValueChangedEvent = true;
            this.sliderCRThreshold.Location = new System.Drawing.Point(4, 196);
            this.sliderCRThreshold.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.sliderCRThreshold.Name = "sliderCRThreshold";
            this.sliderCRThreshold.Size = new System.Drawing.Size(635, 61);
            this.sliderCRThreshold.TabIndex = 43;
            this.sliderCRThreshold.Value = 0;
            this.sliderCRThreshold.ValueChanged += new System.EventHandler(this.sliderPupilThreshold_ValueChanged);
            // 
            // sliderPupilThreshold
            // 
            this.sliderPupilThreshold.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sliderPupilThreshold.EnableValueChangedEvent = true;
            this.sliderPupilThreshold.Location = new System.Drawing.Point(4, 125);
            this.sliderPupilThreshold.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.sliderPupilThreshold.Name = "sliderPupilThreshold";
            this.sliderPupilThreshold.Size = new System.Drawing.Size(635, 61);
            this.sliderPupilThreshold.TabIndex = 42;
            this.sliderPupilThreshold.Value = 0;
            this.sliderPupilThreshold.ValueChanged += new System.EventHandler(this.sliderPupilThreshold_ValueChanged);
            // 
            // EyeTrackingPipelineJOMQuickSettings
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.tableLayoutPanel1);
            this.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.Name = "EyeTrackingPipelineJOMQuickSettings";
            this.Size = new System.Drawing.Size(643, 334);
            ((System.ComponentModel.ISupportInitialize)(this.imageBoxIrisRefeference)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.imageBoxIris)).EndInit();
            this.tableLayoutPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private Emgu.CV.UI.ImageBox imageBoxIrisRefeference;
        private Emgu.CV.UI.ImageBox imageBoxIris;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private SliderTextControl sliderPupilThreshold;
        private SliderTextControl sliderCRThreshold;
        private SliderTextControl sliderIrisRadius;
    }
}
