//<auto-generated />
namespace OpenIris.UI
{
    partial class EyeTrackerTrace
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (this.components != null)
                {
                    this.components.Dispose();
                }
                
                foreach (var chartArea in this.tracesChart.ChartAreas)
                {
                    chartArea.Dispose();
                }

                foreach (var series in this.tracesChart.Series)
                {
                    series.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(EyeTrackerTrace));
            this.tracesChart = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.toolStrip1 = new System.Windows.Forms.ToolStrip();
            this.toolStripDropDownButton1 = new System.Windows.Forms.ToolStripDropDownButton();
            this.horizontalToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.verticalToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.torsionToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.eyeLidsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.pupilToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.headToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.headAccelerationToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.cRToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripLabel1 = new System.Windows.Forms.ToolStripLabel();
            this.toolStripComboBoxSpan = new System.Windows.Forms.ToolStripComboBox();
            this.toolStripLabelFrameRate = new System.Windows.Forms.ToolStripLabel();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.toolStripButtonZoomIn = new System.Windows.Forms.ToolStripButton();
            this.toolStripButtonZoomOut = new System.Windows.Forms.ToolStripButton();
            this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.toolStripButton1 = new System.Windows.Forms.ToolStripButton();
            this.toolStripDropDownButton2 = new System.Windows.Forms.ToolStripDropDownButton();
            this.resetPlotsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.moveVerticalAxisWithDataToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            ((System.ComponentModel.ISupportInitialize)(this.tracesChart)).BeginInit();
            this.toolStrip1.SuspendLayout();
            this.SuspendLayout();
            // 
            // tracesChart
            // 
            this.tracesChart.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tracesChart.Location = new System.Drawing.Point(0, 0);
            this.tracesChart.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.tracesChart.Name = "tracesChart";
            this.tracesChart.Size = new System.Drawing.Size(1754, 600);
            this.tracesChart.TabIndex = 24;
            this.tracesChart.Text = "Trace";
            this.tracesChart.MouseClick += new System.Windows.Forms.MouseEventHandler(this.Chart1_MouseClick);
            // 
            // toolStrip1
            // 
            this.toolStrip1.ImageScalingSize = new System.Drawing.Size(24, 24);
            this.toolStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripDropDownButton1,
            this.toolStripLabel1,
            this.toolStripComboBoxSpan,
            this.toolStripLabelFrameRate,
            this.toolStripSeparator1,
            this.toolStripButtonZoomIn,
            this.toolStripButtonZoomOut,
            this.toolStripSeparator2,
            this.toolStripButton1,
            this.toolStripDropDownButton2});
            this.toolStrip1.Location = new System.Drawing.Point(0, 0);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.Padding = new System.Windows.Forms.Padding(0, 0, 3, 0);
            this.toolStrip1.Size = new System.Drawing.Size(1754, 34);
            this.toolStrip1.TabIndex = 25;
            this.toolStrip1.Text = "toolStrip1";
            // 
            // toolStripDropDownButton1
            // 
            this.toolStripDropDownButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.toolStripDropDownButton1.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.horizontalToolStripMenuItem,
            this.verticalToolStripMenuItem,
            this.torsionToolStripMenuItem,
            this.eyeLidsToolStripMenuItem,
            this.pupilToolStripMenuItem,
            this.headToolStripMenuItem,
            this.headAccelerationToolStripMenuItem,
            this.cRToolStripMenuItem});
            this.toolStripDropDownButton1.Image = ((System.Drawing.Image)(resources.GetObject("toolStripDropDownButton1.Image")));
            this.toolStripDropDownButton1.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripDropDownButton1.Name = "toolStripDropDownButton1";
            this.toolStripDropDownButton1.Size = new System.Drawing.Size(138, 29);
            this.toolStripDropDownButton1.Text = "Select plots ...";
            // 
            // horizontalToolStripMenuItem
            // 
            this.horizontalToolStripMenuItem.Checked = true;
            this.horizontalToolStripMenuItem.CheckOnClick = true;
            this.horizontalToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
            this.horizontalToolStripMenuItem.Name = "horizontalToolStripMenuItem";
            this.horizontalToolStripMenuItem.Size = new System.Drawing.Size(270, 34);
            this.horizontalToolStripMenuItem.Text = "Horizontal";
            this.horizontalToolStripMenuItem.Click += new System.EventHandler(this.SelectPlots_Click);
            // 
            // verticalToolStripMenuItem
            // 
            this.verticalToolStripMenuItem.Checked = true;
            this.verticalToolStripMenuItem.CheckOnClick = true;
            this.verticalToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
            this.verticalToolStripMenuItem.Name = "verticalToolStripMenuItem";
            this.verticalToolStripMenuItem.Size = new System.Drawing.Size(270, 34);
            this.verticalToolStripMenuItem.Text = "Vertical";
            this.verticalToolStripMenuItem.Click += new System.EventHandler(this.visibleChartsToolStripMenuItem_Click);
            // 
            // torsionToolStripMenuItem
            // 
            this.torsionToolStripMenuItem.Checked = true;
            this.torsionToolStripMenuItem.CheckOnClick = true;
            this.torsionToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
            this.torsionToolStripMenuItem.Name = "torsionToolStripMenuItem";
            this.torsionToolStripMenuItem.Size = new System.Drawing.Size(270, 34);
            this.torsionToolStripMenuItem.Text = "Torsion";
            this.torsionToolStripMenuItem.Click += new System.EventHandler(this.visibleChartsToolStripMenuItem_Click);
            // 
            // eyeLidsToolStripMenuItem
            // 
            this.eyeLidsToolStripMenuItem.CheckOnClick = true;
            this.eyeLidsToolStripMenuItem.Name = "eyeLidsToolStripMenuItem";
            this.eyeLidsToolStripMenuItem.Size = new System.Drawing.Size(270, 34);
            this.eyeLidsToolStripMenuItem.Text = "EyeLids";
            this.eyeLidsToolStripMenuItem.Click += new System.EventHandler(this.visibleChartsToolStripMenuItem_Click);
            // 
            // pupilToolStripMenuItem
            // 
            this.pupilToolStripMenuItem.CheckOnClick = true;
            this.pupilToolStripMenuItem.Name = "pupilToolStripMenuItem";
            this.pupilToolStripMenuItem.Size = new System.Drawing.Size(270, 34);
            this.pupilToolStripMenuItem.Text = "Pupil";
            this.pupilToolStripMenuItem.Click += new System.EventHandler(this.visibleChartsToolStripMenuItem_Click);
            // 
            // headToolStripMenuItem
            // 
            this.headToolStripMenuItem.CheckOnClick = true;
            this.headToolStripMenuItem.Name = "headToolStripMenuItem";
            this.headToolStripMenuItem.Size = new System.Drawing.Size(270, 34);
            this.headToolStripMenuItem.Text = "Head velocity";
            this.headToolStripMenuItem.Click += new System.EventHandler(this.visibleChartsToolStripMenuItem_Click);
            // 
            // headAccelerationToolStripMenuItem
            // 
            this.headAccelerationToolStripMenuItem.CheckOnClick = true;
            this.headAccelerationToolStripMenuItem.Name = "headAccelerationToolStripMenuItem";
            this.headAccelerationToolStripMenuItem.Size = new System.Drawing.Size(270, 34);
            this.headAccelerationToolStripMenuItem.Text = "Head acceleration";
            this.headAccelerationToolStripMenuItem.Click += new System.EventHandler(this.visibleChartsToolStripMenuItem_Click);
            // 
            // cRToolStripMenuItem
            // 
            this.cRToolStripMenuItem.CheckOnClick = true;
            this.cRToolStripMenuItem.Name = "cRToolStripMenuItem";
            this.cRToolStripMenuItem.Size = new System.Drawing.Size(270, 34);
            this.cRToolStripMenuItem.Text = "CR";
            this.cRToolStripMenuItem.Click += new System.EventHandler(this.visibleChartsToolStripMenuItem_Click);
            // 
            // toolStripLabel1
            // 
            this.toolStripLabel1.Name = "toolStripLabel1";
            this.toolStripLabel1.Size = new System.Drawing.Size(95, 29);
            this.toolStripLabel1.Text = "Time Span";
            // 
            // toolStripComboBoxSpan
            // 
            this.toolStripComboBoxSpan.Items.AddRange(new object[] {
            "1",
            "2",
            "5",
            "10",
            "20",
            "50",
            "100"});
            this.toolStripComboBoxSpan.Name = "toolStripComboBoxSpan";
            this.toolStripComboBoxSpan.Size = new System.Drawing.Size(180, 34);
            this.toolStripComboBoxSpan.TextUpdate += new System.EventHandler(this.toolStripComboBoxSpan_TextUpdate);
            // 
            // toolStripLabelFrameRate
            // 
            this.toolStripLabelFrameRate.Name = "toolStripLabelFrameRate";
            this.toolStripLabelFrameRate.Size = new System.Drawing.Size(100, 29);
            this.toolStripLabelFrameRate.Text = "Frame rate:";
            // 
            // toolStripSeparator1
            // 
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(6, 34);
            // 
            // toolStripButtonZoomIn
            // 
            this.toolStripButtonZoomIn.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButtonZoomIn.Image = ((System.Drawing.Image)(resources.GetObject("toolStripButtonZoomIn.Image")));
            this.toolStripButtonZoomIn.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonZoomIn.Name = "toolStripButtonZoomIn";
            this.toolStripButtonZoomIn.Size = new System.Drawing.Size(34, 29);
            this.toolStripButtonZoomIn.Text = "Zoom in";
            this.toolStripButtonZoomIn.ToolTipText = "Zoom in (Mouse left click)";
            this.toolStripButtonZoomIn.Click += new System.EventHandler(this.toolStripButtonZoomIn_Click);
            // 
            // toolStripButtonZoomOut
            // 
            this.toolStripButtonZoomOut.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButtonZoomOut.Image = ((System.Drawing.Image)(resources.GetObject("toolStripButtonZoomOut.Image")));
            this.toolStripButtonZoomOut.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonZoomOut.Name = "toolStripButtonZoomOut";
            this.toolStripButtonZoomOut.Size = new System.Drawing.Size(34, 29);
            this.toolStripButtonZoomOut.Text = "Zoom out";
            this.toolStripButtonZoomOut.ToolTipText = "Zoom out (Mouse right click)";
            this.toolStripButtonZoomOut.Click += new System.EventHandler(this.toolStripButtonZoomOut_Click);
            // 
            // toolStripSeparator2
            // 
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new System.Drawing.Size(6, 34);
            // 
            // toolStripButton1
            // 
            this.toolStripButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButton1.Image = ((System.Drawing.Image)(resources.GetObject("toolStripButton1.Image")));
            this.toolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButton1.Name = "toolStripButton1";
            this.toolStripButton1.Size = new System.Drawing.Size(34, 29);
            this.toolStripButton1.Text = "Copy to clipboard";
            this.toolStripButton1.Click += new System.EventHandler(this.toolStripButton1_Click);
            // 
            // toolStripDropDownButton2
            // 
            this.toolStripDropDownButton2.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.toolStripDropDownButton2.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.resetPlotsToolStripMenuItem,
            this.moveVerticalAxisWithDataToolStripMenuItem});
            this.toolStripDropDownButton2.Image = ((System.Drawing.Image)(resources.GetObject("toolStripDropDownButton2.Image")));
            this.toolStripDropDownButton2.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripDropDownButton2.Name = "toolStripDropDownButton2";
            this.toolStripDropDownButton2.Size = new System.Drawing.Size(94, 29);
            this.toolStripDropDownButton2.Text = "Options";
            // 
            // resetPlotsToolStripMenuItem
            // 
            this.resetPlotsToolStripMenuItem.Name = "resetPlotsToolStripMenuItem";
            this.resetPlotsToolStripMenuItem.Size = new System.Drawing.Size(331, 34);
            this.resetPlotsToolStripMenuItem.Text = "Reset plots";
            this.resetPlotsToolStripMenuItem.Click += new System.EventHandler(this.resetPlotsToolStripMenuItem_Click);
            // 
            // moveVerticalAxisWithDataToolStripMenuItem
            // 
            this.moveVerticalAxisWithDataToolStripMenuItem.Checked = true;
            this.moveVerticalAxisWithDataToolStripMenuItem.CheckOnClick = true;
            this.moveVerticalAxisWithDataToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
            this.moveVerticalAxisWithDataToolStripMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.moveVerticalAxisWithDataToolStripMenuItem.Name = "moveVerticalAxisWithDataToolStripMenuItem";
            this.moveVerticalAxisWithDataToolStripMenuItem.Size = new System.Drawing.Size(331, 34);
            this.moveVerticalAxisWithDataToolStripMenuItem.Text = "Move vertical axis with data";
            // 
            // EyeTrackerTrace
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.toolStrip1);
            this.Controls.Add(this.tracesChart);
            this.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.Name = "EyeTrackerTrace";
            this.Size = new System.Drawing.Size(1754, 600);
            ((System.ComponentModel.ISupportInitialize)(this.tracesChart)).EndInit();
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.DataVisualization.Charting.Chart tracesChart;
        private System.Windows.Forms.ToolStrip toolStrip1;
        private System.Windows.Forms.ToolStripLabel toolStripLabel1;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripDropDownButton toolStripDropDownButton1;
        private System.Windows.Forms.ToolStripButton toolStripButton1;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator2;
        private System.Windows.Forms.ToolStripMenuItem horizontalToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem verticalToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem torsionToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem headToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem pupilToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem eyeLidsToolStripMenuItem;
        private System.Windows.Forms.ToolStripButton toolStripButtonZoomIn;
        private System.Windows.Forms.ToolStripButton toolStripButtonZoomOut;
        private System.Windows.Forms.ToolStripComboBox toolStripComboBoxSpan;
        private System.Windows.Forms.ToolStripDropDownButton toolStripDropDownButton2;
        private System.Windows.Forms.ToolStripMenuItem resetPlotsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem moveVerticalAxisWithDataToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem headAccelerationToolStripMenuItem;
        private System.Windows.Forms.ToolStripLabel toolStripLabelFrameRate;
        private System.Windows.Forms.ToolStripMenuItem cRToolStripMenuItem;
    }
}
