//<auto-generated />
namespace OpenIris.UI
{
    partial class EyeTrackerSettingsForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.propertyGridGeneralSettings = new System.Windows.Forms.PropertyGrid();
            this.propertyGridSystemSettings = new System.Windows.Forms.PropertyGrid();
            this.propertyGridTrackingSettings = new System.Windows.Forms.PropertyGrid();
            this.propertyGridCalibrationSettings = new System.Windows.Forms.PropertyGrid();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel1.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.SuspendLayout();
            // 
            // propertyGridGeneralSettings
            // 
            this.propertyGridGeneralSettings.CategoryForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.propertyGridGeneralSettings.Dock = System.Windows.Forms.DockStyle.Fill;
            this.propertyGridGeneralSettings.Location = new System.Drawing.Point(3, 16);
            this.propertyGridGeneralSettings.Name = "propertyGridGeneralSettings";
            this.propertyGridGeneralSettings.Size = new System.Drawing.Size(257, 665);
            this.propertyGridGeneralSettings.TabIndex = 1;
            // 
            // propertyGridSystemSettings
            // 
            this.propertyGridSystemSettings.CategoryForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.propertyGridSystemSettings.Dock = System.Windows.Forms.DockStyle.Fill;
            this.propertyGridSystemSettings.Location = new System.Drawing.Point(3, 16);
            this.propertyGridSystemSettings.Name = "propertyGridSystemSettings";
            this.propertyGridSystemSettings.Size = new System.Drawing.Size(257, 665);
            this.propertyGridSystemSettings.TabIndex = 2;
            // 
            // propertyGridTrackingSettings
            // 
            this.propertyGridTrackingSettings.CategoryForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.propertyGridTrackingSettings.Dock = System.Windows.Forms.DockStyle.Fill;
            this.propertyGridTrackingSettings.Location = new System.Drawing.Point(3, 16);
            this.propertyGridTrackingSettings.Name = "propertyGridTrackingSettings";
            this.propertyGridTrackingSettings.Size = new System.Drawing.Size(257, 665);
            this.propertyGridTrackingSettings.TabIndex = 2;
            // 
            // propertyGridCalibrationSettings
            // 
            this.propertyGridCalibrationSettings.CategoryForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.propertyGridCalibrationSettings.Dock = System.Windows.Forms.DockStyle.Fill;
            this.propertyGridCalibrationSettings.Location = new System.Drawing.Point(3, 16);
            this.propertyGridCalibrationSettings.Name = "propertyGridCalibrationSettings";
            this.propertyGridCalibrationSettings.Size = new System.Drawing.Size(258, 665);
            this.propertyGridCalibrationSettings.TabIndex = 3;
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 4;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel1.Controls.Add(this.groupBox1, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.groupBox2, 1, 0);
            this.tableLayoutPanel1.Controls.Add(this.groupBox3, 2, 0);
            this.tableLayoutPanel1.Controls.Add(this.groupBox4, 3, 0);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 1;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(1077, 690);
            this.tableLayoutPanel1.TabIndex = 3;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.propertyGridGeneralSettings);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox1.Location = new System.Drawing.Point(3, 3);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(263, 684);
            this.groupBox1.TabIndex = 4;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "General settings";
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.propertyGridSystemSettings);
            this.groupBox2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox2.Location = new System.Drawing.Point(272, 3);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(263, 684);
            this.groupBox2.TabIndex = 5;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "System settings";
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.propertyGridTrackingSettings);
            this.groupBox3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox3.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox3.Location = new System.Drawing.Point(541, 3);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(263, 684);
            this.groupBox3.TabIndex = 6;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Tracking settings";
            // 
            // groupBox4
            // 
            this.groupBox4.Controls.Add(this.propertyGridCalibrationSettings);
            this.groupBox4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox4.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox4.Location = new System.Drawing.Point(810, 3);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(264, 684);
            this.groupBox4.TabIndex = 7;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Calibration settings";
            // 
            // EyeTrackerSettingsForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1077, 690);
            this.Controls.Add(this.tableLayoutPanel1);
            this.Name = "EyeTrackerSettingsForm";
            this.Text = "EyeTrackerConfiguration";
            this.tableLayoutPanel1.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.groupBox4.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.PropertyGrid propertyGridGeneralSettings;
        private System.Windows.Forms.PropertyGrid propertyGridTrackingSettings;
        private System.Windows.Forms.PropertyGrid propertyGridSystemSettings;
        private System.Windows.Forms.PropertyGrid propertyGridCalibrationSettings;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.GroupBox groupBox4;
    }
}