// <auto-generated/>
namespace OpenIris.UI
{
    partial class ImageEyeBox
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.imageBoxEye = new Emgu.CV.UI.ImageBox();
            ((System.ComponentModel.ISupportInitialize)(this.imageBoxEye)).BeginInit();
            this.SuspendLayout();
            // 
            // imageBoxEye
            // 
            this.imageBoxEye.BackColor = System.Drawing.Color.Black;
            this.imageBoxEye.Dock = System.Windows.Forms.DockStyle.Fill;
            this.imageBoxEye.FunctionalMode = Emgu.CV.UI.ImageBox.FunctionalModeOption.Minimum;
            this.imageBoxEye.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.Default;
            this.imageBoxEye.Location = new System.Drawing.Point(0, 0);
            this.imageBoxEye.Name = "imageBoxEye";
            this.imageBoxEye.Size = new System.Drawing.Size(480, 360);
            this.imageBoxEye.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.imageBoxEye.TabIndex = 3;
            this.imageBoxEye.TabStop = false;
            // 
            // EyeTrackerImageEyeBox
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.imageBoxEye);
            this.Name = "EyeTrackerImageEyeBox";
            this.Size = new System.Drawing.Size(480, 360);
            ((System.ComponentModel.ISupportInitialize)(this.imageBoxEye)).EndInit();
            this.ResumeLayout(false);

        }

        private Emgu.CV.UI.ImageBox imageBoxEye;

        #endregion
    }
}
