// <auto-generated/>
namespace OpenIris.UI
{
    partial class EyeTrackerGui
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            if ( disposing)
            {
                timerRefreshUI?.Stop();
                timerRefreshUI?.Dispose();

                log?.Dispose();

                eyeTrackerViewModel?.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(EyeTrackerGui));
            this.statusStrip1 = new System.Windows.Forms.StatusStrip();
            this.toolStripStatusLabelImageGrabbingStatus = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel1 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabelProcessingTimeLeftEye = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabelRecording = new System.Windows.Forms.ToolStripStatusLabel();
            this.menuStripMainMenu = new System.Windows.Forms.MenuStrip();
            this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.startTrackingToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.playVideoToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.processVideoToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.stopToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator5 = new System.Windows.Forms.ToolStripSeparator();
            this.configurationToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.recordToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.startStopRecordingToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.viewToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.fullScreenToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.calibrationToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.calibrateToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.cancelCalibrationToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.resetCalibrationToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.resetReferenceToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.loadCalibrationToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.saveCalibrationToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.openSoundRecorderToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.openLogFolderToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.batchAnalysisToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.convertVideoToRGBToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.showIPNetworkInfoToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.trimVideosToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.helpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.aboutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.systemToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.tabPages = new System.Windows.Forms.TabControl();
            this.tabPageStart = new System.Windows.Forms.TabPage();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.linkLabelDataFolder2 = new System.Windows.Forms.LinkLabel();
            this.buttonSelectFolder2 = new System.Windows.Forms.Button();
            this.panel5 = new System.Windows.Forms.Panel();
            this.buttonEditSettings = new System.Windows.Forms.Button();
            this.buttonStartTracking = new System.Windows.Forms.Button();
            this.label5 = new System.Windows.Forms.Label();
            this.buttonPlayVideo = new System.Windows.Forms.Button();
            this.labelEyeTrackingSystem = new System.Windows.Forms.Label();
            this.buttonProcessVideo = new System.Windows.Forms.Button();
            this.tabSetup = new System.Windows.Forms.TabPage();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.panel3 = new System.Windows.Forms.Panel();
            this.panelAlgorithmQuickSettingsLeftEye = new System.Windows.Forms.Panel();
            this.imageBoxLeftEye = new Emgu.CV.UI.ImageBox();
            this.panel2 = new System.Windows.Forms.Panel();
            this.panelAlgorithmQuickSettingsRightEye = new System.Windows.Forms.Panel();
            this.imageBoxRightEye = new Emgu.CV.UI.ImageBox();
            this.panel1 = new System.Windows.Forms.Panel();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.textBoxSession = new System.Windows.Forms.TextBox();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.linkLabelDataFolder = new System.Windows.Forms.LinkLabel();
            this.buttonSelectFolder = new System.Windows.Forms.Button();
            this.buttonResetReference = new System.Windows.Forms.Button();
            this.richTextBox1 = new System.Windows.Forms.RichTextBox();
            this.panelCameraControl = new System.Windows.Forms.Panel();
            this.groupBoxCameraPosition = new System.Windows.Forms.GroupBox();
            this.buttonCenterEyes = new System.Windows.Forms.Button();
            this.buttonMoveLeftEyeDown = new System.Windows.Forms.Button();
            this.imageList2 = new System.Windows.Forms.ImageList(this.components);
            this.buttonMoveRightEyeRight = new System.Windows.Forms.Button();
            this.buttonMoveLeftEyeUp = new System.Windows.Forms.Button();
            this.buttonMoveLeftEyeRight = new System.Windows.Forms.Button();
            this.buttonMoveRightEyeUp = new System.Windows.Forms.Button();
            this.buttonMoveLeftEyeLeft = new System.Windows.Forms.Button();
            this.buttonMoveRightEyeDown = new System.Windows.Forms.Button();
            this.buttonMoveRightEyeLeft = new System.Windows.Forms.Button();
            this.buttonCalibrate = new System.Windows.Forms.Button();
            this.buttonRecord = new System.Windows.Forms.Button();
            this.tabCalibration = new System.Windows.Forms.TabPage();
            this.tabViewer = new System.Windows.Forms.TabPage();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.tableLayoutPanel5 = new System.Windows.Forms.TableLayoutPanel();
            this.eyeTrackerImageEyeBoxLeftEyeSmall = new Emgu.CV.UI.ImageBox();
            this.eyeTrackerImageEyeBoxRightEyeSmall = new Emgu.CV.UI.ImageBox();
            this.panelHeadViewer = new System.Windows.Forms.Panel();
            this.labelHeadData = new System.Windows.Forms.Label();
            this.eyeTrackerTrace = new OpenIris.UI.EyeTrackerTrace();
            this.tabDebug = new System.Windows.Forms.TabPage();
            this.panel6 = new OpenIris.UI.DebugImagesPanel();
            this.tabTiming = new System.Windows.Forms.TabPage();
            this.labelDiagnosticsGrabbing = new System.Windows.Forms.Label();
            this.labelTiming = new System.Windows.Forms.Label();
            this.tabPageLog = new System.Windows.Forms.TabPage();
            this.richTextBoxLogLarge = new System.Windows.Forms.RichTextBox();
            this.imageList1 = new System.Windows.Forms.ImageList(this.components);
            this.panelPlayer = new System.Windows.Forms.Panel();
            this.videoPlayerUI = new OpenIris.UI.VideoPlayerUI();
            this.panel4 = new System.Windows.Forms.Panel();
            this.statusStrip1.SuspendLayout();
            this.menuStripMainMenu.SuspendLayout();
            this.tabPages.SuspendLayout();
            this.tabPageStart.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.panel5.SuspendLayout();
            this.tabSetup.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            this.panel3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.imageBoxLeftEye)).BeginInit();
            this.panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.imageBoxRightEye)).BeginInit();
            this.panel1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.panelCameraControl.SuspendLayout();
            this.groupBoxCameraPosition.SuspendLayout();
            this.tabViewer.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            this.tableLayoutPanel5.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.eyeTrackerImageEyeBoxLeftEyeSmall)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.eyeTrackerImageEyeBoxRightEyeSmall)).BeginInit();
            this.panelHeadViewer.SuspendLayout();
            this.tabDebug.SuspendLayout();
            this.tabTiming.SuspendLayout();
            this.tabPageLog.SuspendLayout();
            this.panelPlayer.SuspendLayout();
            this.panel4.SuspendLayout();
            this.SuspendLayout();
            // 
            // statusStrip1
            // 
            this.statusStrip1.ImageScalingSize = new System.Drawing.Size(32, 32);
            this.statusStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripStatusLabelImageGrabbingStatus,
            this.toolStripStatusLabel1,
            this.toolStripStatusLabelProcessingTimeLeftEye,
            this.toolStripStatusLabelRecording});
            this.statusStrip1.Location = new System.Drawing.Point(0, 678);
            this.statusStrip1.Name = "statusStrip1";
            this.statusStrip1.Size = new System.Drawing.Size(1107, 24);
            this.statusStrip1.TabIndex = 1;
            this.statusStrip1.Text = "statusStrip1";
            // 
            // toolStripStatusLabelImageGrabbingStatus
            // 
            this.toolStripStatusLabelImageGrabbingStatus.Name = "toolStripStatusLabelImageGrabbingStatus";
            this.toolStripStatusLabelImageGrabbingStatus.Size = new System.Drawing.Size(42, 19);
            this.toolStripStatusLabelImageGrabbingStatus.Text = "0.00Hz";
            // 
            // toolStripStatusLabel1
            // 
            this.toolStripStatusLabel1.Name = "toolStripStatusLabel1";
            this.toolStripStatusLabel1.Size = new System.Drawing.Size(754, 19);
            this.toolStripStatusLabel1.Spring = true;
            // 
            // toolStripStatusLabelProcessingTimeLeftEye
            // 
            this.toolStripStatusLabelProcessingTimeLeftEye.BorderSides = System.Windows.Forms.ToolStripStatusLabelBorderSides.Left;
            this.toolStripStatusLabelProcessingTimeLeftEye.Name = "toolStripStatusLabelProcessingTimeLeftEye";
            this.toolStripStatusLabelProcessingTimeLeftEye.Size = new System.Drawing.Size(136, 19);
            this.toolStripStatusLabelProcessingTimeLeftEye.Text = "Processing Time = 0ms;";
            this.toolStripStatusLabelProcessingTimeLeftEye.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // toolStripStatusLabelRecording
            // 
            this.toolStripStatusLabelRecording.BorderSides = System.Windows.Forms.ToolStripStatusLabelBorderSides.Left;
            this.toolStripStatusLabelRecording.Name = "toolStripStatusLabelRecording";
            this.toolStripStatusLabelRecording.Size = new System.Drawing.Size(160, 19);
            this.toolStripStatusLabelRecording.Text = "Frames dropped video rec: 0";
            // 
            // menuStripMainMenu
            // 
            this.menuStripMainMenu.ImageScalingSize = new System.Drawing.Size(32, 32);
            this.menuStripMainMenu.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.fileToolStripMenuItem,
            this.recordToolStripMenuItem,
            this.viewToolStripMenuItem,
            this.calibrationToolStripMenuItem,
            this.toolsToolStripMenuItem,
            this.helpToolStripMenuItem,
            this.systemToolStripMenuItem});
            this.menuStripMainMenu.Location = new System.Drawing.Point(0, 0);
            this.menuStripMainMenu.Name = "menuStripMainMenu";
            this.menuStripMainMenu.Size = new System.Drawing.Size(1107, 24);
            this.menuStripMainMenu.TabIndex = 2;
            this.menuStripMainMenu.Text = "menuStripMainMenu";
            // 
            // fileToolStripMenuItem
            // 
            this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.startTrackingToolStripMenuItem,
            this.playVideoToolStripMenuItem,
            this.processVideoToolStripMenuItem,
            this.stopToolStripMenuItem,
            this.toolStripSeparator5,
            this.configurationToolStripMenuItem,
            this.toolStripSeparator2,
            this.exitToolStripMenuItem});
            this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
            this.fileToolStripMenuItem.Size = new System.Drawing.Size(37, 20);
            this.fileToolStripMenuItem.Text = "File";
            // 
            // startTrackingToolStripMenuItem
            // 
            this.startTrackingToolStripMenuItem.Name = "startTrackingToolStripMenuItem";
            this.startTrackingToolStripMenuItem.ShortcutKeys = System.Windows.Forms.Keys.F1;
            this.startTrackingToolStripMenuItem.Size = new System.Drawing.Size(177, 22);
            this.startTrackingToolStripMenuItem.Text = "Start tracking";
            // 
            // playVideoToolStripMenuItem
            // 
            this.playVideoToolStripMenuItem.Name = "playVideoToolStripMenuItem";
            this.playVideoToolStripMenuItem.ShortcutKeys = System.Windows.Forms.Keys.F2;
            this.playVideoToolStripMenuItem.Size = new System.Drawing.Size(177, 22);
            this.playVideoToolStripMenuItem.Text = "Play video ...";
            // 
            // processVideoToolStripMenuItem
            // 
            this.processVideoToolStripMenuItem.Name = "processVideoToolStripMenuItem";
            this.processVideoToolStripMenuItem.ShortcutKeys = System.Windows.Forms.Keys.F3;
            this.processVideoToolStripMenuItem.Size = new System.Drawing.Size(177, 22);
            this.processVideoToolStripMenuItem.Text = "Process video ...";
            // 
            // stopToolStripMenuItem
            // 
            this.stopToolStripMenuItem.Name = "stopToolStripMenuItem";
            this.stopToolStripMenuItem.ShortcutKeys = System.Windows.Forms.Keys.F5;
            this.stopToolStripMenuItem.Size = new System.Drawing.Size(177, 22);
            this.stopToolStripMenuItem.Text = "Stop";
            // 
            // toolStripSeparator5
            // 
            this.toolStripSeparator5.Name = "toolStripSeparator5";
            this.toolStripSeparator5.Size = new System.Drawing.Size(174, 6);
            // 
            // configurationToolStripMenuItem
            // 
            this.configurationToolStripMenuItem.Name = "configurationToolStripMenuItem";
            this.configurationToolStripMenuItem.Size = new System.Drawing.Size(177, 22);
            this.configurationToolStripMenuItem.Text = "Configuration ...";
            // 
            // toolStripSeparator2
            // 
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new System.Drawing.Size(174, 6);
            // 
            // exitToolStripMenuItem
            // 
            this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            this.exitToolStripMenuItem.Size = new System.Drawing.Size(177, 22);
            this.exitToolStripMenuItem.Text = "Exit";
            // 
            // recordToolStripMenuItem
            // 
            this.recordToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.startStopRecordingToolStripMenuItem});
            this.recordToolStripMenuItem.Name = "recordToolStripMenuItem";
            this.recordToolStripMenuItem.Size = new System.Drawing.Size(56, 20);
            this.recordToolStripMenuItem.Text = "Record";
            // 
            // startStopRecordingToolStripMenuItem
            // 
            this.startStopRecordingToolStripMenuItem.Name = "startStopRecordingToolStripMenuItem";
            this.startStopRecordingToolStripMenuItem.ShortcutKeys = System.Windows.Forms.Keys.F4;
            this.startStopRecordingToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
            this.startStopRecordingToolStripMenuItem.Text = "Start Recording";
            // 
            // viewToolStripMenuItem
            // 
            this.viewToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.fullScreenToolStripMenuItem});
            this.viewToolStripMenuItem.Name = "viewToolStripMenuItem";
            this.viewToolStripMenuItem.Size = new System.Drawing.Size(44, 20);
            this.viewToolStripMenuItem.Text = "View";
            // 
            // fullScreenToolStripMenuItem
            // 
            this.fullScreenToolStripMenuItem.Name = "fullScreenToolStripMenuItem";
            this.fullScreenToolStripMenuItem.Size = new System.Drawing.Size(67, 22);
            // 
            // calibrationToolStripMenuItem
            // 
            this.calibrationToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.calibrateToolStripMenuItem,
            this.cancelCalibrationToolStripMenuItem,
            this.resetCalibrationToolStripMenuItem,
            this.resetReferenceToolStripMenuItem,
            this.loadCalibrationToolStripMenuItem,
            this.saveCalibrationToolStripMenuItem});
            this.calibrationToolStripMenuItem.Name = "calibrationToolStripMenuItem";
            this.calibrationToolStripMenuItem.Size = new System.Drawing.Size(77, 20);
            this.calibrationToolStripMenuItem.Text = "Calibration";
            // 
            // calibrateToolStripMenuItem
            // 
            this.calibrateToolStripMenuItem.Name = "calibrateToolStripMenuItem";
            this.calibrateToolStripMenuItem.ShortcutKeys = System.Windows.Forms.Keys.F9;
            this.calibrateToolStripMenuItem.Size = new System.Drawing.Size(171, 22);
            this.calibrateToolStripMenuItem.Text = "Calibrate";
            // 
            // cancelCalibrationToolStripMenuItem
            // 
            this.cancelCalibrationToolStripMenuItem.Name = "cancelCalibrationToolStripMenuItem";
            this.cancelCalibrationToolStripMenuItem.Size = new System.Drawing.Size(171, 22);
            this.cancelCalibrationToolStripMenuItem.Text = "Cancel calibration";
            // 
            // resetCalibrationToolStripMenuItem
            // 
            this.resetCalibrationToolStripMenuItem.Name = "resetCalibrationToolStripMenuItem";
            this.resetCalibrationToolStripMenuItem.Size = new System.Drawing.Size(171, 22);
            this.resetCalibrationToolStripMenuItem.Text = "Reset calibration";
            // 
            // resetReferenceToolStripMenuItem
            // 
            this.resetReferenceToolStripMenuItem.Name = "resetReferenceToolStripMenuItem";
            this.resetReferenceToolStripMenuItem.Size = new System.Drawing.Size(171, 22);
            this.resetReferenceToolStripMenuItem.Text = "Reset reference";
            // 
            // loadCalibrationToolStripMenuItem
            // 
            this.loadCalibrationToolStripMenuItem.Name = "loadCalibrationToolStripMenuItem";
            this.loadCalibrationToolStripMenuItem.Size = new System.Drawing.Size(171, 22);
            this.loadCalibrationToolStripMenuItem.Text = "Load calibration ...";
            // 
            // saveCalibrationToolStripMenuItem
            // 
            this.saveCalibrationToolStripMenuItem.Name = "saveCalibrationToolStripMenuItem";
            this.saveCalibrationToolStripMenuItem.Size = new System.Drawing.Size(171, 22);
            this.saveCalibrationToolStripMenuItem.Text = "Save calibration ...";
            // 
            // toolsToolStripMenuItem
            // 
            this.toolsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.openSoundRecorderToolStripMenuItem,
            this.openLogFolderToolStripMenuItem,
            this.batchAnalysisToolStripMenuItem,
            this.convertVideoToRGBToolStripMenuItem,
            this.showIPNetworkInfoToolStripMenuItem,
            this.trimVideosToolStripMenuItem});
            this.toolsToolStripMenuItem.Name = "toolsToolStripMenuItem";
            this.toolsToolStripMenuItem.Size = new System.Drawing.Size(46, 20);
            this.toolsToolStripMenuItem.Text = "Tools";
            // 
            // openSoundRecorderToolStripMenuItem
            // 
            this.openSoundRecorderToolStripMenuItem.Name = "openSoundRecorderToolStripMenuItem";
            this.openSoundRecorderToolStripMenuItem.Size = new System.Drawing.Size(190, 22);
            this.openSoundRecorderToolStripMenuItem.Text = "Open Sound Recorder";
            // 
            // openLogFolderToolStripMenuItem
            // 
            this.openLogFolderToolStripMenuItem.Name = "openLogFolderToolStripMenuItem";
            this.openLogFolderToolStripMenuItem.Size = new System.Drawing.Size(190, 22);
            this.openLogFolderToolStripMenuItem.Text = "Open log folder";
            // 
            // batchAnalysisToolStripMenuItem
            // 
            this.batchAnalysisToolStripMenuItem.Name = "batchAnalysisToolStripMenuItem";
            this.batchAnalysisToolStripMenuItem.Size = new System.Drawing.Size(190, 22);
            this.batchAnalysisToolStripMenuItem.Text = "Batch analysis";
            // 
            // convertVideoToRGBToolStripMenuItem
            // 
            this.convertVideoToRGBToolStripMenuItem.Name = "convertVideoToRGBToolStripMenuItem";
            this.convertVideoToRGBToolStripMenuItem.Size = new System.Drawing.Size(190, 22);
            this.convertVideoToRGBToolStripMenuItem.Text = "ConvertVideoToRGB";
            // 
            // showIPNetworkInfoToolStripMenuItem
            // 
            this.showIPNetworkInfoToolStripMenuItem.Name = "showIPNetworkInfoToolStripMenuItem";
            this.showIPNetworkInfoToolStripMenuItem.Size = new System.Drawing.Size(190, 22);
            this.showIPNetworkInfoToolStripMenuItem.Text = "Show IP network info";
            // 
            // trimVideosToolStripMenuItem
            // 
            this.trimVideosToolStripMenuItem.Name = "trimVideosToolStripMenuItem";
            this.trimVideosToolStripMenuItem.Size = new System.Drawing.Size(190, 22);
            this.trimVideosToolStripMenuItem.Text = "Trim videos";
            // 
            // helpToolStripMenuItem
            // 
            this.helpToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.aboutToolStripMenuItem});
            this.helpToolStripMenuItem.Name = "helpToolStripMenuItem";
            this.helpToolStripMenuItem.Size = new System.Drawing.Size(44, 20);
            this.helpToolStripMenuItem.Text = "Help";
            // 
            // aboutToolStripMenuItem
            // 
            this.aboutToolStripMenuItem.Name = "aboutToolStripMenuItem";
            this.aboutToolStripMenuItem.Size = new System.Drawing.Size(107, 22);
            this.aboutToolStripMenuItem.Text = "About";
            // 
            // systemToolStripMenuItem
            // 
            this.systemToolStripMenuItem.Name = "systemToolStripMenuItem";
            this.systemToolStripMenuItem.Size = new System.Drawing.Size(57, 20);
            this.systemToolStripMenuItem.Text = "System";
            // 
            // tabPages
            // 
            this.tabPages.Controls.Add(this.tabPageStart);
            this.tabPages.Controls.Add(this.tabSetup);
            this.tabPages.Controls.Add(this.tabCalibration);
            this.tabPages.Controls.Add(this.tabViewer);
            this.tabPages.Controls.Add(this.tabDebug);
            this.tabPages.Controls.Add(this.tabTiming);
            this.tabPages.Controls.Add(this.tabPageLog);
            this.tabPages.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabPages.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tabPages.ImageList = this.imageList1;
            this.tabPages.Location = new System.Drawing.Point(0, 0);
            this.tabPages.Name = "tabPages";
            this.tabPages.SelectedIndex = 0;
            this.tabPages.Size = new System.Drawing.Size(1107, 623);
            this.tabPages.TabIndex = 28;
            // 
            // tabPageStart
            // 
            this.tabPageStart.Controls.Add(this.groupBox3);
            this.tabPageStart.Controls.Add(this.panel5);
            this.tabPageStart.Location = new System.Drawing.Point(4, 24);
            this.tabPageStart.Name = "tabPageStart";
            this.tabPageStart.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageStart.Size = new System.Drawing.Size(1099, 595);
            this.tabPageStart.TabIndex = 6;
            this.tabPageStart.Text = "Start";
            this.tabPageStart.UseVisualStyleBackColor = true;
            // 
            // groupBox3
            // 
            this.groupBox3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.groupBox3.Controls.Add(this.linkLabelDataFolder2);
            this.groupBox3.Controls.Add(this.buttonSelectFolder2);
            this.groupBox3.Location = new System.Drawing.Point(427, 464);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(280, 58);
            this.groupBox3.TabIndex = 41;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Data folder:";
            // 
            // linkLabelDataFolder2
            // 
            this.linkLabelDataFolder2.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.linkLabelDataFolder2.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.linkLabelDataFolder2.Location = new System.Drawing.Point(6, 20);
            this.linkLabelDataFolder2.Name = "linkLabelDataFolder2";
            this.linkLabelDataFolder2.Size = new System.Drawing.Size(223, 24);
            this.linkLabelDataFolder2.TabIndex = 33;
            this.linkLabelDataFolder2.TabStop = true;
            this.linkLabelDataFolder2.Text = "Folder";
            // 
            // buttonSelectFolder2
            // 
            this.buttonSelectFolder2.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonSelectFolder2.Location = new System.Drawing.Point(235, 20);
            this.buttonSelectFolder2.Name = "buttonSelectFolder2";
            this.buttonSelectFolder2.Size = new System.Drawing.Size(38, 24);
            this.buttonSelectFolder2.TabIndex = 39;
            this.buttonSelectFolder2.Text = "...";
            this.buttonSelectFolder2.UseVisualStyleBackColor = true;
            // 
            // panel5
            // 
            this.panel5.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.panel5.Controls.Add(this.buttonEditSettings);
            this.panel5.Controls.Add(this.buttonStartTracking);
            this.panel5.Controls.Add(this.label5);
            this.panel5.Controls.Add(this.buttonPlayVideo);
            this.panel5.Controls.Add(this.labelEyeTrackingSystem);
            this.panel5.Controls.Add(this.buttonProcessVideo);
            this.panel5.Location = new System.Drawing.Point(427, 143);
            this.panel5.Name = "panel5";
            this.panel5.Size = new System.Drawing.Size(280, 315);
            this.panel5.TabIndex = 3;
            // 
            // buttonEditSettings
            // 
            this.buttonEditSettings.Location = new System.Drawing.Point(0, 260);
            this.buttonEditSettings.Name = "buttonEditSettings";
            this.buttonEditSettings.Size = new System.Drawing.Size(273, 52);
            this.buttonEditSettings.TabIndex = 3;
            this.buttonEditSettings.Text = "Edit settings";
            this.buttonEditSettings.UseVisualStyleBackColor = true;
            // 
            // buttonStartTracking
            // 
            this.buttonStartTracking.Location = new System.Drawing.Point(3, 3);
            this.buttonStartTracking.Name = "buttonStartTracking";
            this.buttonStartTracking.Size = new System.Drawing.Size(273, 48);
            this.buttonStartTracking.TabIndex = 0;
            this.buttonStartTracking.Text = "Start Tracking";
            this.buttonStartTracking.UseVisualStyleBackColor = true;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(5, 67);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(122, 15);
            this.label5.TabIndex = 2;
            this.label5.Text = "Eyetracking System : ";
            // 
            // buttonPlayVideo
            // 
            this.buttonPlayVideo.Location = new System.Drawing.Point(3, 109);
            this.buttonPlayVideo.Name = "buttonPlayVideo";
            this.buttonPlayVideo.Size = new System.Drawing.Size(273, 52);
            this.buttonPlayVideo.TabIndex = 0;
            this.buttonPlayVideo.Text = "Play video";
            this.buttonPlayVideo.UseVisualStyleBackColor = true;
            // 
            // labelEyeTrackingSystem
            // 
            this.labelEyeTrackingSystem.AutoSize = true;
            this.labelEyeTrackingSystem.Location = new System.Drawing.Point(132, 67);
            this.labelEyeTrackingSystem.Name = "labelEyeTrackingSystem";
            this.labelEyeTrackingSystem.Size = new System.Drawing.Size(11, 15);
            this.labelEyeTrackingSystem.TabIndex = 1;
            this.labelEyeTrackingSystem.Text = "-";
            // 
            // buttonProcessVideo
            // 
            this.buttonProcessVideo.Location = new System.Drawing.Point(3, 167);
            this.buttonProcessVideo.Name = "buttonProcessVideo";
            this.buttonProcessVideo.Size = new System.Drawing.Size(273, 52);
            this.buttonProcessVideo.TabIndex = 0;
            this.buttonProcessVideo.Text = "Process Video";
            this.buttonProcessVideo.UseVisualStyleBackColor = true;
            // 
            // tabSetup
            // 
            this.tabSetup.BackColor = System.Drawing.SystemColors.Control;
            this.tabSetup.Controls.Add(this.tableLayoutPanel1);
            this.tabSetup.ImageIndex = 0;
            this.tabSetup.Location = new System.Drawing.Point(4, 24);
            this.tabSetup.Name = "tabSetup";
            this.tabSetup.Padding = new System.Windows.Forms.Padding(3);
            this.tabSetup.Size = new System.Drawing.Size(1099, 595);
            this.tabSetup.TabIndex = 0;
            this.tabSetup.Text = "Set up";
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.BackColor = System.Drawing.SystemColors.Control;
            this.tableLayoutPanel1.ColumnCount = 3;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 268F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 301F));
            this.tableLayoutPanel1.Controls.Add(this.panel3, 2, 0);
            this.tableLayoutPanel1.Controls.Add(this.panel2, 1, 0);
            this.tableLayoutPanel1.Controls.Add(this.panel1, 0, 0);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 1;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 589F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 589F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(1093, 589);
            this.tableLayoutPanel1.TabIndex = 28;
            // 
            // panel3
            // 
            this.panel3.Controls.Add(this.panelAlgorithmQuickSettingsLeftEye);
            this.panel3.Controls.Add(this.imageBoxLeftEye);
            this.panel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel3.Location = new System.Drawing.Point(683, 3);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(407, 583);
            this.panel3.TabIndex = 41;
            // 
            // panelAlgorithmQuickSettingsLeftEye
            // 
            this.panelAlgorithmQuickSettingsLeftEye.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panelAlgorithmQuickSettingsLeftEye.Location = new System.Drawing.Point(4, 369);
            this.panelAlgorithmQuickSettingsLeftEye.Margin = new System.Windows.Forms.Padding(2);
            this.panelAlgorithmQuickSettingsLeftEye.Name = "panelAlgorithmQuickSettingsLeftEye";
            this.panelAlgorithmQuickSettingsLeftEye.Size = new System.Drawing.Size(401, 227);
            this.panelAlgorithmQuickSettingsLeftEye.TabIndex = 32;
            // 
            // imageBoxLeftEye
            // 
            this.imageBoxLeftEye.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.imageBoxLeftEye.BackColor = System.Drawing.SystemColors.Control;
            this.imageBoxLeftEye.FunctionalMode = Emgu.CV.UI.ImageBox.FunctionalModeOption.RightClickMenu;
            this.imageBoxLeftEye.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.Bicubic;
            this.imageBoxLeftEye.Location = new System.Drawing.Point(4, 3);
            this.imageBoxLeftEye.Name = "imageBoxLeftEye";
            this.imageBoxLeftEye.Size = new System.Drawing.Size(401, 360);
            this.imageBoxLeftEye.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.imageBoxLeftEye.TabIndex = 29;
            this.imageBoxLeftEye.TabStop = false;
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.SystemColors.Control;
            this.panel2.Controls.Add(this.panelAlgorithmQuickSettingsRightEye);
            this.panel2.Controls.Add(this.imageBoxRightEye);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel2.Location = new System.Drawing.Point(271, 3);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(406, 583);
            this.panel2.TabIndex = 41;
            // 
            // panelAlgorithmQuickSettingsRightEye
            // 
            this.panelAlgorithmQuickSettingsRightEye.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panelAlgorithmQuickSettingsRightEye.Location = new System.Drawing.Point(6, 369);
            this.panelAlgorithmQuickSettingsRightEye.Margin = new System.Windows.Forms.Padding(2);
            this.panelAlgorithmQuickSettingsRightEye.Name = "panelAlgorithmQuickSettingsRightEye";
            this.panelAlgorithmQuickSettingsRightEye.Size = new System.Drawing.Size(401, 227);
            this.panelAlgorithmQuickSettingsRightEye.TabIndex = 31;
            // 
            // imageBoxRightEye
            // 
            this.imageBoxRightEye.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.imageBoxRightEye.BackColor = System.Drawing.SystemColors.Control;
            this.imageBoxRightEye.FunctionalMode = Emgu.CV.UI.ImageBox.FunctionalModeOption.RightClickMenu;
            this.imageBoxRightEye.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.Bicubic;
            this.imageBoxRightEye.Location = new System.Drawing.Point(6, 3);
            this.imageBoxRightEye.Name = "imageBoxRightEye";
            this.imageBoxRightEye.Size = new System.Drawing.Size(401, 360);
            this.imageBoxRightEye.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.imageBoxRightEye.TabIndex = 30;
            this.imageBoxRightEye.TabStop = false;
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.groupBox2);
            this.panel1.Controls.Add(this.groupBox1);
            this.panel1.Controls.Add(this.buttonResetReference);
            this.panel1.Controls.Add(this.richTextBox1);
            this.panel1.Controls.Add(this.panelCameraControl);
            this.panel1.Controls.Add(this.buttonCalibrate);
            this.panel1.Controls.Add(this.buttonRecord);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel1.Location = new System.Drawing.Point(3, 3);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(262, 583);
            this.panel1.TabIndex = 27;
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.textBoxSession);
            this.groupBox2.Location = new System.Drawing.Point(3, 3);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(256, 54);
            this.groupBox2.TabIndex = 41;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Session name:";
            // 
            // textBoxSession
            // 
            this.textBoxSession.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textBoxSession.Location = new System.Drawing.Point(6, 20);
            this.textBoxSession.Name = "textBoxSession";
            this.textBoxSession.Size = new System.Drawing.Size(239, 26);
            this.textBoxSession.TabIndex = 34;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.linkLabelDataFolder);
            this.groupBox1.Controls.Add(this.buttonSelectFolder);
            this.groupBox1.Location = new System.Drawing.Point(3, 55);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(256, 58);
            this.groupBox1.TabIndex = 40;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Data folder:";
            // 
            // linkLabelDataFolder
            // 
            this.linkLabelDataFolder.BackColor = System.Drawing.SystemColors.Control;
            this.linkLabelDataFolder.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.linkLabelDataFolder.Location = new System.Drawing.Point(6, 20);
            this.linkLabelDataFolder.Name = "linkLabelDataFolder";
            this.linkLabelDataFolder.Size = new System.Drawing.Size(195, 24);
            this.linkLabelDataFolder.TabIndex = 33;
            this.linkLabelDataFolder.TabStop = true;
            this.linkLabelDataFolder.Text = "Folder";
            // 
            // buttonSelectFolder
            // 
            this.buttonSelectFolder.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonSelectFolder.Location = new System.Drawing.Point(207, 20);
            this.buttonSelectFolder.Name = "buttonSelectFolder";
            this.buttonSelectFolder.Size = new System.Drawing.Size(38, 24);
            this.buttonSelectFolder.TabIndex = 39;
            this.buttonSelectFolder.Text = "...";
            this.buttonSelectFolder.UseVisualStyleBackColor = true;
            // 
            // buttonResetReference
            // 
            this.buttonResetReference.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonResetReference.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonResetReference.Location = new System.Drawing.Point(3, 279);
            this.buttonResetReference.Name = "buttonResetReference";
            this.buttonResetReference.Size = new System.Drawing.Size(256, 41);
            this.buttonResetReference.TabIndex = 38;
            this.buttonResetReference.Text = "Reset reference";
            this.buttonResetReference.UseVisualStyleBackColor = true;
            // 
            // richTextBox1
            // 
            this.richTextBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.richTextBox1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.richTextBox1.Font = new System.Drawing.Font("Consolas", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.richTextBox1.Location = new System.Drawing.Point(3, 384);
            this.richTextBox1.Name = "richTextBox1";
            this.richTextBox1.ReadOnly = true;
            this.richTextBox1.Size = new System.Drawing.Size(256, 197);
            this.richTextBox1.TabIndex = 37;
            this.richTextBox1.Text = "";
            this.richTextBox1.WordWrap = false;
            // 
            // panelCameraControl
            // 
            this.panelCameraControl.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panelCameraControl.Controls.Add(this.groupBoxCameraPosition);
            this.panelCameraControl.Location = new System.Drawing.Point(3, 114);
            this.panelCameraControl.Name = "panelCameraControl";
            this.panelCameraControl.Size = new System.Drawing.Size(258, 116);
            this.panelCameraControl.TabIndex = 36;
            // 
            // groupBoxCameraPosition
            // 
            this.groupBoxCameraPosition.Controls.Add(this.buttonCenterEyes);
            this.groupBoxCameraPosition.Controls.Add(this.buttonMoveLeftEyeDown);
            this.groupBoxCameraPosition.Controls.Add(this.buttonMoveRightEyeRight);
            this.groupBoxCameraPosition.Controls.Add(this.buttonMoveLeftEyeUp);
            this.groupBoxCameraPosition.Controls.Add(this.buttonMoveLeftEyeRight);
            this.groupBoxCameraPosition.Controls.Add(this.buttonMoveRightEyeUp);
            this.groupBoxCameraPosition.Controls.Add(this.buttonMoveLeftEyeLeft);
            this.groupBoxCameraPosition.Controls.Add(this.buttonMoveRightEyeDown);
            this.groupBoxCameraPosition.Controls.Add(this.buttonMoveRightEyeLeft);
            this.groupBoxCameraPosition.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBoxCameraPosition.ForeColor = System.Drawing.SystemColors.ControlText;
            this.groupBoxCameraPosition.Location = new System.Drawing.Point(0, 0);
            this.groupBoxCameraPosition.Name = "groupBoxCameraPosition";
            this.groupBoxCameraPosition.Size = new System.Drawing.Size(258, 116);
            this.groupBoxCameraPosition.TabIndex = 32;
            this.groupBoxCameraPosition.TabStop = false;
            this.groupBoxCameraPosition.Text = "Camera position";
            // 
            // buttonCenterEyes
            // 
            this.buttonCenterEyes.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonCenterEyes.Location = new System.Drawing.Point(69, 22);
            this.buttonCenterEyes.Name = "buttonCenterEyes";
            this.buttonCenterEyes.Size = new System.Drawing.Size(123, 86);
            this.buttonCenterEyes.TabIndex = 4;
            this.buttonCenterEyes.Text = "Center eyes";
            this.buttonCenterEyes.UseVisualStyleBackColor = true;
            // 
            // buttonMoveLeftEyeDown
            // 
            this.buttonMoveLeftEyeDown.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.buttonMoveLeftEyeDown.ImageIndex = 0;
            this.buttonMoveLeftEyeDown.ImageList = this.imageList2;
            this.buttonMoveLeftEyeDown.Location = new System.Drawing.Point(198, 83);
            this.buttonMoveLeftEyeDown.Name = "buttonMoveLeftEyeDown";
            this.buttonMoveLeftEyeDown.Size = new System.Drawing.Size(54, 24);
            this.buttonMoveLeftEyeDown.TabIndex = 29;
            this.buttonMoveLeftEyeDown.UseVisualStyleBackColor = true;
            // 
            // imageList2
            // 
            this.imageList2.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageList2.ImageStream")));
            this.imageList2.TransparentColor = System.Drawing.Color.Transparent;
            this.imageList2.Images.SetKeyName(0, "down.ico");
            this.imageList2.Images.SetKeyName(1, "left.ico");
            this.imageList2.Images.SetKeyName(2, "right.ico");
            this.imageList2.Images.SetKeyName(3, "up.ico");
            // 
            // buttonMoveRightEyeRight
            // 
            this.buttonMoveRightEyeRight.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.buttonMoveRightEyeRight.ImageIndex = 2;
            this.buttonMoveRightEyeRight.ImageList = this.imageList2;
            this.buttonMoveRightEyeRight.Location = new System.Drawing.Point(39, 52);
            this.buttonMoveRightEyeRight.Name = "buttonMoveRightEyeRight";
            this.buttonMoveRightEyeRight.Size = new System.Drawing.Size(24, 24);
            this.buttonMoveRightEyeRight.TabIndex = 27;
            this.buttonMoveRightEyeRight.UseVisualStyleBackColor = true;
            // 
            // buttonMoveLeftEyeUp
            // 
            this.buttonMoveLeftEyeUp.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.buttonMoveLeftEyeUp.ImageIndex = 3;
            this.buttonMoveLeftEyeUp.ImageList = this.imageList2;
            this.buttonMoveLeftEyeUp.Location = new System.Drawing.Point(198, 21);
            this.buttonMoveLeftEyeUp.Name = "buttonMoveLeftEyeUp";
            this.buttonMoveLeftEyeUp.Size = new System.Drawing.Size(54, 24);
            this.buttonMoveLeftEyeUp.TabIndex = 28;
            this.buttonMoveLeftEyeUp.UseVisualStyleBackColor = true;
            // 
            // buttonMoveLeftEyeRight
            // 
            this.buttonMoveLeftEyeRight.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.buttonMoveLeftEyeRight.ImageIndex = 2;
            this.buttonMoveLeftEyeRight.ImageList = this.imageList2;
            this.buttonMoveLeftEyeRight.Location = new System.Drawing.Point(228, 51);
            this.buttonMoveLeftEyeRight.Name = "buttonMoveLeftEyeRight";
            this.buttonMoveLeftEyeRight.Size = new System.Drawing.Size(24, 24);
            this.buttonMoveLeftEyeRight.TabIndex = 27;
            this.buttonMoveLeftEyeRight.UseVisualStyleBackColor = true;
            // 
            // buttonMoveRightEyeUp
            // 
            this.buttonMoveRightEyeUp.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.buttonMoveRightEyeUp.ImageIndex = 3;
            this.buttonMoveRightEyeUp.ImageList = this.imageList2;
            this.buttonMoveRightEyeUp.Location = new System.Drawing.Point(9, 21);
            this.buttonMoveRightEyeUp.Name = "buttonMoveRightEyeUp";
            this.buttonMoveRightEyeUp.Size = new System.Drawing.Size(54, 24);
            this.buttonMoveRightEyeUp.TabIndex = 25;
            this.buttonMoveRightEyeUp.UseVisualStyleBackColor = true;
            // 
            // buttonMoveLeftEyeLeft
            // 
            this.buttonMoveLeftEyeLeft.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.buttonMoveLeftEyeLeft.ImageIndex = 1;
            this.buttonMoveLeftEyeLeft.ImageList = this.imageList2;
            this.buttonMoveLeftEyeLeft.Location = new System.Drawing.Point(198, 51);
            this.buttonMoveLeftEyeLeft.Name = "buttonMoveLeftEyeLeft";
            this.buttonMoveLeftEyeLeft.Size = new System.Drawing.Size(24, 24);
            this.buttonMoveLeftEyeLeft.TabIndex = 27;
            this.buttonMoveLeftEyeLeft.UseVisualStyleBackColor = true;
            // 
            // buttonMoveRightEyeDown
            // 
            this.buttonMoveRightEyeDown.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.buttonMoveRightEyeDown.ImageIndex = 0;
            this.buttonMoveRightEyeDown.ImageList = this.imageList2;
            this.buttonMoveRightEyeDown.Location = new System.Drawing.Point(9, 83);
            this.buttonMoveRightEyeDown.Name = "buttonMoveRightEyeDown";
            this.buttonMoveRightEyeDown.Size = new System.Drawing.Size(54, 24);
            this.buttonMoveRightEyeDown.TabIndex = 26;
            this.buttonMoveRightEyeDown.UseVisualStyleBackColor = true;
            // 
            // buttonMoveRightEyeLeft
            // 
            this.buttonMoveRightEyeLeft.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.buttonMoveRightEyeLeft.ImageIndex = 1;
            this.buttonMoveRightEyeLeft.ImageList = this.imageList2;
            this.buttonMoveRightEyeLeft.Location = new System.Drawing.Point(9, 52);
            this.buttonMoveRightEyeLeft.Name = "buttonMoveRightEyeLeft";
            this.buttonMoveRightEyeLeft.Size = new System.Drawing.Size(24, 24);
            this.buttonMoveRightEyeLeft.TabIndex = 27;
            this.buttonMoveRightEyeLeft.UseVisualStyleBackColor = true;
            // 
            // buttonCalibrate
            // 
            this.buttonCalibrate.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonCalibrate.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonCalibrate.Location = new System.Drawing.Point(3, 232);
            this.buttonCalibrate.Name = "buttonCalibrate";
            this.buttonCalibrate.Size = new System.Drawing.Size(256, 41);
            this.buttonCalibrate.TabIndex = 4;
            this.buttonCalibrate.Text = "Calibrate";
            this.buttonCalibrate.UseVisualStyleBackColor = true;
            // 
            // buttonRecord
            // 
            this.buttonRecord.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonRecord.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonRecord.Location = new System.Drawing.Point(3, 326);
            this.buttonRecord.Name = "buttonRecord";
            this.buttonRecord.Size = new System.Drawing.Size(256, 52);
            this.buttonRecord.TabIndex = 32;
            this.buttonRecord.Text = "Start recording";
            this.buttonRecord.UseVisualStyleBackColor = true;
            // 
            // tabCalibration
            // 
            this.tabCalibration.ImageIndex = 2;
            this.tabCalibration.Location = new System.Drawing.Point(4, 24);
            this.tabCalibration.Name = "tabCalibration";
            this.tabCalibration.Padding = new System.Windows.Forms.Padding(3);
            this.tabCalibration.Size = new System.Drawing.Size(1099, 595);
            this.tabCalibration.TabIndex = 4;
            this.tabCalibration.Text = "Calibration";
            this.tabCalibration.UseVisualStyleBackColor = true;
            // 
            // tabViewer
            // 
            this.tabViewer.BackColor = System.Drawing.SystemColors.Control;
            this.tabViewer.Controls.Add(this.splitContainer1);
            this.tabViewer.ImageIndex = 3;
            this.tabViewer.Location = new System.Drawing.Point(4, 24);
            this.tabViewer.Name = "tabViewer";
            this.tabViewer.Padding = new System.Windows.Forms.Padding(3);
            this.tabViewer.Size = new System.Drawing.Size(1099, 595);
            this.tabViewer.TabIndex = 1;
            this.tabViewer.Text = "Viewer";
            // 
            // splitContainer1
            // 
            this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer1.Location = new System.Drawing.Point(3, 3);
            this.splitContainer1.Name = "splitContainer1";
            this.splitContainer1.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // splitContainer1.Panel1
            // 
            this.splitContainer1.Panel1.Controls.Add(this.tableLayoutPanel5);
            // 
            // splitContainer1.Panel2
            // 
            this.splitContainer1.Panel2.Controls.Add(this.eyeTrackerTrace);
            this.splitContainer1.Size = new System.Drawing.Size(1093, 589);
            this.splitContainer1.SplitterDistance = 135;
            this.splitContainer1.TabIndex = 0;
            // 
            // tableLayoutPanel5
            // 
            this.tableLayoutPanel5.ColumnCount = 3;
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tableLayoutPanel5.Controls.Add(this.eyeTrackerImageEyeBoxLeftEyeSmall, 1, 0);
            this.tableLayoutPanel5.Controls.Add(this.eyeTrackerImageEyeBoxRightEyeSmall, 0, 0);
            this.tableLayoutPanel5.Controls.Add(this.panelHeadViewer, 2, 0);
            this.tableLayoutPanel5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel5.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel5.Name = "tableLayoutPanel5";
            this.tableLayoutPanel5.RowCount = 1;
            this.tableLayoutPanel5.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel5.Size = new System.Drawing.Size(1093, 135);
            this.tableLayoutPanel5.TabIndex = 37;
            // 
            // eyeTrackerImageEyeBoxLeftEyeSmall
            // 
            this.eyeTrackerImageEyeBoxLeftEyeSmall.Dock = System.Windows.Forms.DockStyle.Fill;
            this.eyeTrackerImageEyeBoxLeftEyeSmall.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.Bicubic;
            this.eyeTrackerImageEyeBoxLeftEyeSmall.Location = new System.Drawing.Point(440, 3);
            this.eyeTrackerImageEyeBoxLeftEyeSmall.Name = "eyeTrackerImageEyeBoxLeftEyeSmall";
            this.eyeTrackerImageEyeBoxLeftEyeSmall.Size = new System.Drawing.Size(431, 129);
            this.eyeTrackerImageEyeBoxLeftEyeSmall.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.eyeTrackerImageEyeBoxLeftEyeSmall.TabIndex = 34;
            this.eyeTrackerImageEyeBoxLeftEyeSmall.TabStop = false;
            // 
            // eyeTrackerImageEyeBoxRightEyeSmall
            // 
            this.eyeTrackerImageEyeBoxRightEyeSmall.Dock = System.Windows.Forms.DockStyle.Fill;
            this.eyeTrackerImageEyeBoxRightEyeSmall.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.Bicubic;
            this.eyeTrackerImageEyeBoxRightEyeSmall.Location = new System.Drawing.Point(3, 3);
            this.eyeTrackerImageEyeBoxRightEyeSmall.Name = "eyeTrackerImageEyeBoxRightEyeSmall";
            this.eyeTrackerImageEyeBoxRightEyeSmall.Size = new System.Drawing.Size(431, 129);
            this.eyeTrackerImageEyeBoxRightEyeSmall.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.eyeTrackerImageEyeBoxRightEyeSmall.TabIndex = 0;
            this.eyeTrackerImageEyeBoxRightEyeSmall.TabStop = false;
            // 
            // panelHeadViewer
            // 
            this.panelHeadViewer.Controls.Add(this.labelHeadData);
            this.panelHeadViewer.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelHeadViewer.Location = new System.Drawing.Point(877, 3);
            this.panelHeadViewer.Name = "panelHeadViewer";
            this.panelHeadViewer.Size = new System.Drawing.Size(213, 129);
            this.panelHeadViewer.TabIndex = 35;
            // 
            // labelHeadData
            // 
            this.labelHeadData.AutoSize = true;
            this.labelHeadData.Font = new System.Drawing.Font("Consolas", 15F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelHeadData.Location = new System.Drawing.Point(3, 0);
            this.labelHeadData.Name = "labelHeadData";
            this.labelHeadData.Size = new System.Drawing.Size(76, 23);
            this.labelHeadData.TabIndex = 0;
            this.labelHeadData.Text = "label6";
            // 
            // eyeTrackerTrace
            // 
            this.eyeTrackerTrace.Dock = System.Windows.Forms.DockStyle.Fill;
            this.eyeTrackerTrace.Location = new System.Drawing.Point(0, 0);
            this.eyeTrackerTrace.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.eyeTrackerTrace.Name = "eyeTrackerTrace";
            this.eyeTrackerTrace.Size = new System.Drawing.Size(1093, 450);
            this.eyeTrackerTrace.TabIndex = 0;
            // 
            // tabDebug
            // 
            this.tabDebug.Controls.Add(this.panel6);
            this.tabDebug.Location = new System.Drawing.Point(4, 24);
            this.tabDebug.Name = "tabDebug";
            this.tabDebug.Padding = new System.Windows.Forms.Padding(3);
            this.tabDebug.Size = new System.Drawing.Size(1099, 595);
            this.tabDebug.TabIndex = 2;
            this.tabDebug.Text = "Debug";
            this.tabDebug.UseVisualStyleBackColor = true;
            // 
            // panel6
            // 
            this.panel6.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel6.Location = new System.Drawing.Point(3, 3);
            this.panel6.Name = "panel6";
            this.panel6.Size = new System.Drawing.Size(1093, 589);
            this.panel6.TabIndex = 0;
            // 
            // tabTiming
            // 
            this.tabTiming.Controls.Add(this.labelDiagnosticsGrabbing);
            this.tabTiming.Controls.Add(this.labelTiming);
            this.tabTiming.Location = new System.Drawing.Point(4, 24);
            this.tabTiming.Name = "tabTiming";
            this.tabTiming.Padding = new System.Windows.Forms.Padding(3);
            this.tabTiming.Size = new System.Drawing.Size(1099, 595);
            this.tabTiming.TabIndex = 3;
            this.tabTiming.Text = "Timing";
            this.tabTiming.UseVisualStyleBackColor = true;
            // 
            // labelDiagnosticsGrabbing
            // 
            this.labelDiagnosticsGrabbing.AutoSize = true;
            this.labelDiagnosticsGrabbing.Font = new System.Drawing.Font("Courier New", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelDiagnosticsGrabbing.Location = new System.Drawing.Point(612, 37);
            this.labelDiagnosticsGrabbing.Name = "labelDiagnosticsGrabbing";
            this.labelDiagnosticsGrabbing.Size = new System.Drawing.Size(182, 28);
            this.labelDiagnosticsGrabbing.TabIndex = 1;
            this.labelDiagnosticsGrabbing.Text = "Testing diagnostics Label\r\n how does it look\r\n";
            // 
            // labelTiming
            // 
            this.labelTiming.AutoSize = true;
            this.labelTiming.Font = new System.Drawing.Font("Courier New", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelTiming.Location = new System.Drawing.Point(24, 23);
            this.labelTiming.Name = "labelTiming";
            this.labelTiming.Size = new System.Drawing.Size(119, 42);
            this.labelTiming.TabIndex = 0;
            this.labelTiming.Text = "Testing timing \r\nLabel\r\nhow does it look\r\n";
            // 
            // tabPageLog
            // 
            this.tabPageLog.Controls.Add(this.richTextBoxLogLarge);
            this.tabPageLog.Location = new System.Drawing.Point(4, 24);
            this.tabPageLog.Name = "tabPageLog";
            this.tabPageLog.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageLog.Size = new System.Drawing.Size(1099, 595);
            this.tabPageLog.TabIndex = 5;
            this.tabPageLog.Text = "Log";
            this.tabPageLog.UseVisualStyleBackColor = true;
            // 
            // richTextBoxLogLarge
            // 
            this.richTextBoxLogLarge.Dock = System.Windows.Forms.DockStyle.Fill;
            this.richTextBoxLogLarge.Font = new System.Drawing.Font("Consolas", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.richTextBoxLogLarge.Location = new System.Drawing.Point(3, 3);
            this.richTextBoxLogLarge.Name = "richTextBoxLogLarge";
            this.richTextBoxLogLarge.ReadOnly = true;
            this.richTextBoxLogLarge.Size = new System.Drawing.Size(1093, 589);
            this.richTextBoxLogLarge.TabIndex = 0;
            this.richTextBoxLogLarge.Text = "";
            this.richTextBoxLogLarge.WordWrap = false;
            // 
            // imageList1
            // 
            this.imageList1.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageList1.ImageStream")));
            this.imageList1.TransparentColor = System.Drawing.Color.Transparent;
            this.imageList1.Images.SetKeyName(0, "setup");
            this.imageList1.Images.SetKeyName(1, "eye");
            this.imageList1.Images.SetKeyName(2, "target");
            this.imageList1.Images.SetKeyName(3, "if_line_chart_172493 (1).ico");
            // 
            // panelPlayer
            // 
            this.panelPlayer.Controls.Add(this.videoPlayerUI);
            this.panelPlayer.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panelPlayer.Location = new System.Drawing.Point(0, 623);
            this.panelPlayer.Name = "panelPlayer";
            this.panelPlayer.Size = new System.Drawing.Size(1107, 31);
            this.panelPlayer.TabIndex = 1;
            // 
            // videoPlayerUI
            // 
            this.videoPlayerUI.Dock = System.Windows.Forms.DockStyle.Fill;
            this.videoPlayerUI.Location = new System.Drawing.Point(0, 0);
            this.videoPlayerUI.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.videoPlayerUI.Name = "videoPlayerUI";
            this.videoPlayerUI.ProgressDisplayType = OpenIris.UI.VideoPlayerUI.ProgressDisplay.FrameNumber;
            this.videoPlayerUI.Size = new System.Drawing.Size(1107, 31);
            this.videoPlayerUI.TabIndex = 0;
            // 
            // panel4
            // 
            this.panel4.Controls.Add(this.tabPages);
            this.panel4.Controls.Add(this.panelPlayer);
            this.panel4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel4.Location = new System.Drawing.Point(0, 24);
            this.panel4.Name = "panel4";
            this.panel4.Size = new System.Drawing.Size(1107, 654);
            this.panel4.TabIndex = 29;
            // 
            // EyeTrackerGui
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1107, 702);
            this.Controls.Add(this.panel4);
            this.Controls.Add(this.statusStrip1);
            this.Controls.Add(this.menuStripMainMenu);
            this.DoubleBuffered = true;
            this.MainMenuStrip = this.menuStripMainMenu;
            this.MinimumSize = new System.Drawing.Size(636, 468);
            this.Name = "EyeTrackerGui";
            this.Text = "EyeTracker";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.EyeTrackerGUI_FormClosing);
            this.statusStrip1.ResumeLayout(false);
            this.statusStrip1.PerformLayout();
            this.menuStripMainMenu.ResumeLayout(false);
            this.menuStripMainMenu.PerformLayout();
            this.tabPages.ResumeLayout(false);
            this.tabPageStart.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.panel5.ResumeLayout(false);
            this.panel5.PerformLayout();
            this.tabSetup.ResumeLayout(false);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.panel3.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.imageBoxLeftEye)).EndInit();
            this.panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.imageBoxRightEye)).EndInit();
            this.panel1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.panelCameraControl.ResumeLayout(false);
            this.groupBoxCameraPosition.ResumeLayout(false);
            this.tabViewer.ResumeLayout(false);
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            this.tableLayoutPanel5.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.eyeTrackerImageEyeBoxLeftEyeSmall)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.eyeTrackerImageEyeBoxRightEyeSmall)).EndInit();
            this.panelHeadViewer.ResumeLayout(false);
            this.panelHeadViewer.PerformLayout();
            this.tabDebug.ResumeLayout(false);
            this.tabTiming.ResumeLayout(false);
            this.tabTiming.PerformLayout();
            this.tabPageLog.ResumeLayout(false);
            this.panelPlayer.ResumeLayout(false);
            this.panel4.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.StatusStrip statusStrip1;
        private System.Windows.Forms.MenuStrip menuStripMainMenu;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator2;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabelImageGrabbingStatus;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabelProcessingTimeLeftEye;
        private System.Windows.Forms.ToolStripMenuItem configurationToolStripMenuItem;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabelRecording;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.TabControl tabPages;
        private System.Windows.Forms.TabPage tabSetup;
        private System.Windows.Forms.TabPage tabViewer;
        private System.Windows.Forms.ToolStripMenuItem playVideoToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem processVideoToolStripMenuItem;
        private System.Windows.Forms.Panel panelPlayer;
        private System.Windows.Forms.ToolStripMenuItem startTrackingToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem stopToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator5;
        private System.Windows.Forms.TabPage tabDebug;
        private System.Windows.Forms.Panel panel4;
        private System.Windows.Forms.TabPage tabTiming;
        private System.Windows.Forms.Label labelTiming;
        private System.Windows.Forms.Label labelDiagnosticsGrabbing;
        private System.Windows.Forms.ToolStripMenuItem recordToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem startStopRecordingToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem viewToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem fullScreenToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem calibrationToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem calibrateToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem saveCalibrationToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem loadCalibrationToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem toolsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem openSoundRecorderToolStripMenuItem;
        private System.Windows.Forms.SplitContainer splitContainer1;
        private EyeTrackerTrace eyeTrackerTrace;
        private System.Windows.Forms.ToolStripMenuItem openLogFolderToolStripMenuItem;
        private Emgu.CV.UI.ImageBox imageBoxLeftEye;
        private Emgu.CV.UI.ImageBox imageBoxRightEye;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel5;
        private Emgu.CV.UI.ImageBox eyeTrackerImageEyeBoxLeftEyeSmall;
        private Emgu.CV.UI.ImageBox eyeTrackerImageEyeBoxRightEyeSmall;
        private System.Windows.Forms.ToolStripMenuItem batchAnalysisToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem convertVideoToRGBToolStripMenuItem;
        private System.Windows.Forms.TabPage tabCalibration;
        private System.Windows.Forms.TabPage tabPageLog;
        private System.Windows.Forms.RichTextBox richTextBoxLogLarge;
        private System.Windows.Forms.ToolStripMenuItem resetReferenceToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem resetCalibrationToolStripMenuItem;
        private VideoPlayerUI videoPlayerUI;
        private System.Windows.Forms.ToolStripMenuItem showIPNetworkInfoToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem;
        private System.Windows.Forms.Panel panel3;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.TabPage tabPageStart;
        private System.Windows.Forms.Button buttonStartTracking;
        private System.Windows.Forms.Button buttonProcessVideo;
        private System.Windows.Forms.Button buttonPlayVideo;
        private System.Windows.Forms.Label labelEyeTrackingSystem;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Panel panel5;
        private System.Windows.Forms.Button buttonEditSettings;
        private System.Windows.Forms.Panel panelHeadViewer;
        private System.Windows.Forms.Label labelHeadData;
        private System.Windows.Forms.ImageList imageList1;
        private System.Windows.Forms.ToolStripMenuItem trimVideosToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem cancelCalibrationToolStripMenuItem;
        private System.Windows.Forms.ImageList imageList2;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Button buttonSelectFolder;
        private System.Windows.Forms.Button buttonResetReference;
        private System.Windows.Forms.RichTextBox richTextBox1;
        private System.Windows.Forms.Panel panelCameraControl;
        private System.Windows.Forms.GroupBox groupBoxCameraPosition;
        private System.Windows.Forms.Button buttonCenterEyes;
        private System.Windows.Forms.Button buttonMoveLeftEyeDown;
        private System.Windows.Forms.Button buttonMoveRightEyeRight;
        private System.Windows.Forms.Button buttonMoveLeftEyeUp;
        private System.Windows.Forms.Button buttonMoveLeftEyeRight;
        private System.Windows.Forms.Button buttonMoveRightEyeUp;
        private System.Windows.Forms.Button buttonMoveLeftEyeLeft;
        private System.Windows.Forms.Button buttonMoveRightEyeDown;
        private System.Windows.Forms.Button buttonMoveRightEyeLeft;
        private System.Windows.Forms.LinkLabel linkLabelDataFolder;
        private System.Windows.Forms.Button buttonCalibrate;
        private System.Windows.Forms.TextBox textBoxSession;
        private System.Windows.Forms.Button buttonRecord;
        private System.Windows.Forms.Panel panelAlgorithmQuickSettingsLeftEye;
        private System.Windows.Forms.Panel panelAlgorithmQuickSettingsRightEye;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel1;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.LinkLabel linkLabelDataFolder2;
        private System.Windows.Forms.Button buttonSelectFolder2;
        private OpenIris.UI.DebugImagesPanel panel6;
        private System.Windows.Forms.ToolStripMenuItem systemToolStripMenuItem;
    }
}